 [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/zach-hill-27506748"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/midumass"

 [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/midumass"
